name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        default: "vx.x.x"

jobs:
  builds:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.0"

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --ldflags="-s -w -X main.VERSION=${{ inputs.version }}-$(git rev-parse --short HEAD)" -o bin/bulkdl_linux_amd64 cmd/bulkdl/*.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build --ldflags="-s -w -X main.VERSION=${{ inputs.version }}-$(git rev-parse --short HEAD)" -o bin/bulkdl_windows_amd64.exe cmd/bulkdl/*.go

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            bin/bulkdl_linux_amd64
            bin/bulkdl_windows_amd64.exe

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - builds
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: files
          path: files

      - name: Create Release and Upload Artifacts
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.version }}
          draft: true
          prerelease: true
          automatic_release_tag: ${{ inputs.version }}
          files: |
            files/*
